In [3]:
import numpy as np
import pandas as pd
from yaml import safe_load
import os
from tqdm import tqdm

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [1]:
!ls "/content/drive/MyDrive"

ls: cannot access '/content/drive/MyDrive': No such file or directory

In [5]:
import zipfile
zip_path="/content/drive/MyDrive/t20.zip"

with zipfile.ZipFile(zip_path,'r') as zip_ref:
  zip_ref.extractall('/content')

In [6]:
!find /content -type d | grep t20

/content/it20s
/content/t20s

In [7]:
filenames=os.listdir("/content/t20s")

In [8]:
filenames[0:5]

['1483068.yaml',
 '1074965.yaml',
 '1531150.yaml',
 '1407102.yaml',
 '1298175.yaml']

In [11]:
all_match_data = [] # List to hold all processed match dictionaries

for file in tqdm(filenames):
    file_path = os.path.join('/content/t20s', file) # Use os.path.join for better path handling
    try:
        with open(file_path, 'r') as f:
            data = safe_load(f)
            if isinstance(data, dict): # Ensure the loaded data is a dictionary
                data['match_id'] = file.replace('.yaml', '')
                all_match_data.append(data)
            else:
                print(f"Skipping file {file}: Expected dictionary but got {type(data)}")
    except Exception as e:
        print(f"Error processing file {file}: {e}")

# Normalize all collected data at once
final_df = pd.json_normalize(all_match_data)

display(final_df.head())

 41%|████      | 2164/5342 [06:04<08:39,  6.12it/s]

Skipping file README.txt: Expected dictionary but got <class 'str'>

100%|██████████| 5342/5342 [14:54<00:00,  5.97it/s]

,innings,match_id,meta.data_version,meta.created,meta.revision,info.balls_per_over,info.city,info.dates,info.gender,info.match_type,...,info.registry.people.Robiul Khan,info.registry.people.Aparna Gurumurthy,info.registry.people.TU Montero,info.registry.people.Bilal Shah,info.registry.people.J Sonia,info.registry.people.GJ McCarter,info.registry.people.J Anderson,info.registry.people.GJ Batty,info.registry.people.T Birbal,info.registry.people.C Rice
0,"[{'1st innings': {'team': 'Croatia', 'deliveri...",1483068,0.92,2025-05-05,1,6,Marsa,[2025-05-05],female,T20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'Ireland', 'deliveri...",1074965,0.91,2017-01-18,2,6,NaN,[2017-01-18],male,T20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'Italy', 'deliveries...",1531150,0.92,2026-04-20,1,6,Kigali City,[2026-04-18],female,T20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Kenya', 'deliveries...",1407102,0.92,2023-11-29,1,6,Windhoek,[2023-11-27],male,T20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",1298175,0.92,2022-11-07,2,6,Adelaide,[2022-11-06],male,T20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
final_df.head()

,innings,meta.data_version,meta.created,meta.revision,info.balls_per_over,info.city,info.dates,info.gender,info.match_type,info.match_type_number,...,info.registry.people.H Beresford-Peirse,info.registry.people.Hardeep Singh,info.registry.people.S Bevin,info.registry.people.Farooq Ali Khan,info.registry.people.Song Yangyang,info.registry.people.MJ Potts,info.registry.people.K Srinath,info.registry.people.CS Baugh,info.registry.people.LS Baker,info.registry.people.SE Findlay
0,"[{'1st innings': {'team': 'Croatia', 'deliveri...",0.92,2025-05-05,1,6,Marsa,[2025-05-05],female,T20,2277.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'Ireland', 'deliveri...",0.91,2017-01-18,2,6,NaN,[2017-01-18],male,T20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'Italy', 'deliveries...",0.92,2026-04-20,1,6,Kigali City,[2026-04-18],female,T20,2725.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Kenya', 'deliveries...",0.92,2023-11-29,1,6,Windhoek,[2023-11-27],male,T20,2368.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",0.92,2022-11-07,2,6,Adelaide,[2022-11-06],male,T20,1872.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
backup=final_df.copy()

In [24]:
final_df=backup.copy()

In [25]:
final_df['info.gender'].value_counts()

info.gender
male      3366
female    1975
Name: count, dtype: int64

In [26]:
final_df=final_df[final_df['info.gender']=='male']
final_df.drop(columns=['info.gender'],inplace=True)
final_df

,innings,match_id,meta.data_version,meta.created,meta.revision,info.balls_per_over,info.city,info.dates,info.match_type,info.match_type_number,...,info.registry.people.Robiul Khan,info.registry.people.Aparna Gurumurthy,info.registry.people.TU Montero,info.registry.people.Bilal Shah,info.registry.people.J Sonia,info.registry.people.GJ McCarter,info.registry.people.J Anderson,info.registry.people.GJ Batty,info.registry.people.T Birbal,info.registry.people.C Rice
1,"[{'1st innings': {'team': 'Ireland', 'deliveri...",1074965,0.91,2017-01-18,2,6,NaN,[2017-01-18],T20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Kenya', 'deliveries...",1407102,0.92,2023-11-29,1,6,Windhoek,[2023-11-27],T20,2368.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",1298175,0.92,2022-11-07,2,6,Adelaide,[2022-11-06],T20,1872.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"[{'1st innings': {'team': 'Mozambique', 'deliv...",1343770,0.92,2022-12-04,1,6,Kigali City,[2022-12-01],T20,1927.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",1485508,0.92,2025-07-10,1,6,Kandy,[2025-07-10],T20,3299.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5333,"[{'1st innings': {'team': 'Malawi', 'deliverie...",1283033,0.92,2021-10-20,2,6,Kigali City,[2021-10-20],T20,1323.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dbd19fb8
5334,"[{'1st innings': {'team': 'Nepal', 'deliveries...",1489968,0.92,2025-09-29,1,6,Sharjah,[2025-09-27],T20,3477.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5336,"[{'1st innings': {'team': 'Singapore', 'delive...",1482100,0.92,2025-05-02,1,6,Kuala Lumpur,[2025-05-02],T20,3171.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5337,"[{'1st innings': {'team': 'Malawi', 'deliverie...",1526845,0.92,2026-03-25,1,6,Accra,[2026-03-25],T20,3786.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5339,"[{'1st innings': {'team': 'Pakistan', 'deliver...",1157375,0.91,2020-07-06,1,6,Abu Dhabi,[2018-10-31],T20,705.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
final_df.drop(columns=[
    'meta.data_version',
    'meta.created',
    'meta.revision',
    'info.outcome.bowl_out',
    'info.bowl_out',
    'info.supersubs.South Africa',
    'info.supersubs.New Zealand',
    'info.outcome.eliminator',
    'info.outcome.result',
    'info.outcome.method',
    'info.neutral_venue',
    'info.match_type_number',
    'info.outcome.by.runs',
    'info.outcome.by.wickets'
],inplace=True)

# Calculate NaN percentage for each column
nan_threshold = 0.7 # Define a threshold for NaN values (e.g., 70%)
nan_columns = final_df.columns[final_df.isnull().sum() / len(final_df) > nan_threshold]

if not nan_columns.empty:
    print(f"Dropping {len(nan_columns)} columns with more than {nan_threshold*100}% NaN values.")
    final_df.drop(columns=nan_columns, inplace=True)
else:
    print("No columns found with more than 70% NaN values to drop after previous operations.")

print(f"Shape of DataFrame after dropping high-NaN columns: {final_df.shape}")
display(final_df.head())

Dropping 8145 columns with more than 70.0% NaN values.
Shape of DataFrame after dropping high-NaN columns: (3366, 14)

,innings,match_id,info.balls_per_over,info.city,info.dates,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.winner,info.toss.decision,info.umpires,info.venue
1,"[{'1st innings': {'team': 'Ireland', 'deliveri...",1074965,6,NaN,[2017-01-18],T20,Ireland,20,[WB Rankin],"[United Arab Emirates, Ireland]",Ireland,bat,"[Ahmed Shah Durrani, BB Pradhan]",Dubai International Cricket Stadium
3,"[{'1st innings': {'team': 'Kenya', 'deliveries...",1407102,6,Windhoek,[2023-11-27],T20,Namibia,20,[JN Frylinck],"[Kenya, Namibia]",Namibia,field,"[L Rusere, S Dambanevana]","United Cricket Club Ground, Windhoek"
4,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",1298175,6,Adelaide,[2022-11-06],T20,Pakistan,20,[Shaheen Shah Afridi],"[Bangladesh, Pakistan]",Bangladesh,bat,"[AT Holdstock, JS Wilson]",Adelaide Oval
5,"[{'1st innings': {'team': 'Mozambique', 'deliv...",1343770,6,Kigali City,[2022-12-01],T20,Nigeria,20,[AA Onikoyi],"[Mozambique, Nigeria]",Nigeria,field,"[F Mutizwa, S Kintu]",Gahanga International Cricket Stadium. Rwanda
11,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",1485508,6,Kandy,[2025-07-10],T20,Sri Lanka,20,[BKG Mendis],"[Bangladesh, Sri Lanka]",Sri Lanka,field,"[RR Wimalasiri, RSA Palliyaguruge]",Pallekele International Cricket Stadium

In [28]:
final_df.head()

,innings,match_id,info.balls_per_over,info.city,info.dates,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.teams,info.toss.winner,info.toss.decision,info.umpires,info.venue
1,"[{'1st innings': {'team': 'Ireland', 'deliveri...",1074965,6,NaN,[2017-01-18],T20,Ireland,20,[WB Rankin],"[United Arab Emirates, Ireland]",Ireland,bat,"[Ahmed Shah Durrani, BB Pradhan]",Dubai International Cricket Stadium
3,"[{'1st innings': {'team': 'Kenya', 'deliveries...",1407102,6,Windhoek,[2023-11-27],T20,Namibia,20,[JN Frylinck],"[Kenya, Namibia]",Namibia,field,"[L Rusere, S Dambanevana]","United Cricket Club Ground, Windhoek"
4,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",1298175,6,Adelaide,[2022-11-06],T20,Pakistan,20,[Shaheen Shah Afridi],"[Bangladesh, Pakistan]",Bangladesh,bat,"[AT Holdstock, JS Wilson]",Adelaide Oval
5,"[{'1st innings': {'team': 'Mozambique', 'deliv...",1343770,6,Kigali City,[2022-12-01],T20,Nigeria,20,[AA Onikoyi],"[Mozambique, Nigeria]",Nigeria,field,"[F Mutizwa, S Kintu]",Gahanga International Cricket Stadium. Rwanda
11,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",1485508,6,Kandy,[2025-07-10],T20,Sri Lanka,20,[BKG Mendis],"[Bangladesh, Sri Lanka]",Sri Lanka,field,"[RR Wimalasiri, RSA Palliyaguruge]",Pallekele International Cricket Stadium

In [30]:
final_df.shape

(3366, 14)

In [31]:
final_df['info.match_type'].value_counts()

info.match_type
T20    3366
Name: count, dtype: int64

In [32]:
final_df['info.overs'].value_counts()

info.overs
20    3358
50       8
Name: count, dtype: int64

In [33]:
final_df = final_df[final_df['info.overs'] == 20]
final_df.drop(columns=['info.overs','info.match_type'],inplace=True)
final_df

/tmp/ipykernel_2685/3157072726.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.drop(columns=['info.overs','info.match_type'],inplace=True)

,innings,match_id,info.balls_per_over,info.city,info.dates,info.outcome.winner,info.player_of_match,info.teams,info.toss.winner,info.toss.decision,info.umpires,info.venue
1,"[{'1st innings': {'team': 'Ireland', 'deliveri...",1074965,6,NaN,[2017-01-18],Ireland,[WB Rankin],"[United Arab Emirates, Ireland]",Ireland,bat,"[Ahmed Shah Durrani, BB Pradhan]",Dubai International Cricket Stadium
3,"[{'1st innings': {'team': 'Kenya', 'deliveries...",1407102,6,Windhoek,[2023-11-27],Namibia,[JN Frylinck],"[Kenya, Namibia]",Namibia,field,"[L Rusere, S Dambanevana]","United Cricket Club Ground, Windhoek"
4,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",1298175,6,Adelaide,[2022-11-06],Pakistan,[Shaheen Shah Afridi],"[Bangladesh, Pakistan]",Bangladesh,bat,"[AT Holdstock, JS Wilson]",Adelaide Oval
5,"[{'1st innings': {'team': 'Mozambique', 'deliv...",1343770,6,Kigali City,[2022-12-01],Nigeria,[AA Onikoyi],"[Mozambique, Nigeria]",Nigeria,field,"[F Mutizwa, S Kintu]",Gahanga International Cricket Stadium. Rwanda
11,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",1485508,6,Kandy,[2025-07-10],Sri Lanka,[BKG Mendis],"[Bangladesh, Sri Lanka]",Sri Lanka,field,"[RR Wimalasiri, RSA Palliyaguruge]",Pallekele International Cricket Stadium
...,...,...,...,...,...,...,...,...,...,...,...,...
5333,"[{'1st innings': {'team': 'Malawi', 'deliverie...",1283033,6,Kigali City,[2021-10-20],Malawi,[Sami Sohail],"[Malawi, Seychelles]",Malawi,bat,"[C Phiri, Itangishaka Olivier]",Gahanga International Cricket Stadium. Rwanda
5334,"[{'1st innings': {'team': 'Nepal', 'deliveries...",1489968,6,Sharjah,[2025-09-27],Nepal,[RK Paudel],"[Nepal, West Indies]",West Indies,field,"[BB Pradhan, DN Subedi]",Sharjah Cricket Stadium
5336,"[{'1st innings': {'team': 'Singapore', 'delive...",1482100,6,Kuala Lumpur,[2025-05-02],Singapore,[H Venkataram],"[Singapore, Thailand]",Singapore,bat,"[D Sevakumaran, V Kalidas]","Bayuemas Oval, Kuala Lumpur"
5337,"[{'1st innings': {'team': 'Malawi', 'deliverie...",1526845,6,Accra,[2026-03-25],Ghana,[Nitesh Hooda],"[Malawi, Ghana]",Ghana,field,"[A Jacobs, R D'Mello]","Achimota Senior Secondary School A Field, Accra"
5339,"[{'1st innings': {'team': 'Pakistan', 'deliver...",1157375,6,Abu Dhabi,[2018-10-31],Pakistan,[Mohammad Hafeez],"[Pakistan, New Zealand]",Pakistan,bat,"[Asif Yaqoob, Shozab Raza]",Sheikh Zayed Stadium

In [34]:
import pickle
pickle.dump(final_df,open('dataset_level1.pkl','wb'))

In [35]:
#matches = pickle.load(open('dataset_level1.pkl','rb'))

In [42]:
matches.iloc[0]['innings'][0]['1st innings']['deliveries']

[{0.1: {'batsman': 'PR Stirling',
   'bowler': 'Mohammad Naveed',
   'extras': {'wides': 1},
   'non_striker': 'SW Poynter',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {0.2: {'batsman': 'PR Stirling',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'SW Poynter',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.3: {'batsman': 'PR Stirling',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'SW Poynter',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.4: {'batsman': 'PR Stirling',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'SW Poynter',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.5: {'batsman': 'PR Stirling',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'SW Poynter',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.6: {'batsman': 'PR Stirling',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'SW Poynter',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {0.7: {'batsman': 'PR Stirling',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'SW Poynter',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {1.1: {'batsman': 'SW Poynter',
   'bowler': 'Amjad Javed',
   'non_striker': 'PR Stirling',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.2: {'batsman': 'SW Poynter',
   'bowler': 'Amjad Javed',
   'non_striker': 'PR Stirling',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {1.3: {'batsman': 'SW Poynter',
   'bowler': 'Amjad Javed',
   'non_striker': 'PR Stirling',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {1.4: {'batsman': 'PR Stirling',
   'bowler': 'Amjad Javed',
   'non_striker': 'SW Poynter',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {1.5: {'batsman': 'SW Poynter',
   'bowler': 'Amjad Javed',
   'non_striker': 'PR Stirling',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {1.6: {'batsman': 'PR Stirling',
   'bowler': 'Amjad Javed',
   'non_striker': 'SW Poynter',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {2.1: {'batsman': 'PR Stirling',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'SW Poynter',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {2.2: {'batsman': 'PR Stirling',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'SW Poynter',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {2.3: {'batsman': 'PR Stirling',
   'bowler': 'Mohammad Naveed',
   'extras': {'noballs': 1},
   'non_striker': 'SW Poynter',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {2.4: {'batsman': 'PR Stirling',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'SW Poynter',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {2.5: {'batsman': 'PR Stirling',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'SW Poynter',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {2.6: {'batsman': 'SW Poynter',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'PR Stirling',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {2.7: {'batsman': 'PR Stirling',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'SW Poynter',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {3.1: {'batsman': 'SW Poynter',
   'bowler': 'Ahmed Raza',
   'extras': {'byes': 1},
   'non_striker': 'PR Stirling',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {3.2: {'batsman': 'PR Stirling',
   'bowler': 'Ahmed Raza',
   'non_striker': 'SW Poynter',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {3.3: {'batsman': 'PR Stirling',
   'bowler': 'Ahmed Raza',
   'non_striker': 'SW Poynter',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {3.4: {'batsman': 'PR Stirling',
   'bowler': 'Ahmed Raza',
   'non_striker': 'SW Poynter',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {3.5: {'batsman': 'PR Stirling',
   'bowler': 'Ahmed Raza',
   'non_striker': 'SW Poynter',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {3.6: {'batsman': 'PR Stirling',
   'bowler': 'Ahmed Raza',
   'non_striker': 'SW Poynter',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {4.1: {'batsman': 'SW Poynter',
   'bowler': 'Amjad Javed',
   'non_striker': 'PR Stirling',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['Shaiman Anwar'],
    'kind': 'caught',
    'player_out': 'SW Poynter'}}},
 {4.2: {'batsman': 'WTS Porterfield',
   'bowler': 'Amjad Javed',
   'non_striker': 'PR Stirling',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {4.3: {'batsman': 'WTS Porterfield',
   'bowler': 'Amjad Javed',
   'non_striker': 'PR Stirling',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {4.4: {'batsman': 'WTS Porterfield',
   'bowler': 'Amjad Javed',
   'non_striker': 'PR Stirling',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {4.5: {'batsman': 'WTS Porterfield',
   'bowler': 'Amjad Javed',
   'non_striker': 'PR Stirling',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {4.6: {'batsman': 'WTS Porterfield',
   'bowler': 'Amjad Javed',
   'non_striker': 'PR Stirling',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.1: {'batsman': 'PR Stirling',
   'bowler': 'Rohan Mustafa',
   'non_striker': 'WTS Porterfield',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {5.2: {'batsman': 'PR Stirling',
   'bowler': 'Rohan Mustafa',
   'non_striker': 'WTS Porterfield',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.3: {'batsman': 'PR Stirling',
   'bowler': 'Rohan Mustafa',
   'non_striker': 'WTS Porterfield',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.4: {'batsman': 'PR Stirling',
   'bowler': 'Rohan Mustafa',
   'non_striker': 'WTS Porterfield',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.5: {'batsman': 'PR Stirling',
   'bowler': 'Rohan Mustafa',
   'non_striker': 'WTS Porterfield',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.6: {'batsman': 'PR Stirling',
   'bowler': 'Rohan Mustafa',
   'non_striker': 'WTS Porterfield',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {6.1: {'batsman': 'WTS Porterfield',
   'bowler': 'Amjad Javed',
   'extras': {'legbyes': 1},
   'non_striker': 'PR Stirling',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {6.2: {'batsman': 'PR Stirling',
   'bowler': 'Amjad Javed',
   'non_striker': 'WTS Porterfield',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.3: {'batsman': 'WTS Porterfield',
   'bowler': 'Amjad Javed',
   'non_striker': 'PR Stirling',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {6.4: {'batsman': 'WTS Porterfield',
   'bowler': 'Amjad Javed',
   'extras': {'wides': 1},
   'non_striker': 'PR Stirling',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {6.5: {'batsman': 'WTS Porterfield',
   'bowler': 'Amjad Javed',
   'non_striker': 'PR Stirling',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {6.6: {'batsman': 'WTS Porterfield',
   'bowler': 'Amjad Javed',
   'non_striker': 'PR Stirling',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['Rameez Shahzad'],
    'kind': 'caught',
    'player_out': 'WTS Porterfield'}}},
 {6.7: {'batsman': "KJ O'Brien",
   'bowler': 'Amjad Javed',
   'non_striker': 'PR Stirling',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.1: {'batsman': "KJ O'Brien",
   'bowler': 'Imran Haider',
   'non_striker': 'PR Stirling',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.2: {'batsman': 'PR Stirling',
   'bowler': 'Imran Haider',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {7.3: {'batsman': 'PR Stirling',
   'bowler': 'Imran Haider',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {7.4: {'batsman': 'PR Stirling',
   'bowler': 'Imran Haider',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.5: {'batsman': "KJ O'Brien",
   'bowler': 'Imran Haider',
   'non_striker': 'PR Stirling',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.6: {'batsman': 'PR Stirling',
   'bowler': 'Imran Haider',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'kind': 'bowled', 'player_out': 'PR Stirling'}}},
 {8.1: {'batsman': "KJ O'Brien",
   'bowler': 'Amjad Javed',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {8.2: {'batsman': "KJ O'Brien",
   'bowler': 'Amjad Javed',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {8.3: {'batsman': "KJ O'Brien",
   'bowler': 'Amjad Javed',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {8.4: {'batsman': "KJ O'Brien",
   'bowler': 'Amjad Javed',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {8.5: {'batsman': "KJ O'Brien",
   'bowler': 'Amjad Javed',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {8.6: {'batsman': "KJ O'Brien",
   'bowler': 'Amjad Javed',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.1: {'batsman': "KJ O'Brien",
   'bowler': 'Imran Haider',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {9.2: {'batsman': "KJ O'Brien",
   'bowler': 'Imran Haider',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.3: {'batsman': 'GC Wilson',
   'bowler': 'Imran Haider',
   'extras': {'legbyes': 1},
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {9.4: {'batsman': "KJ O'Brien",
   'bowler': 'Imran Haider',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {9.5: {'batsman': "KJ O'Brien",
   'bowler': 'Imran Haider',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {9.6: {'batsman': "KJ O'Brien",
   'bowler': 'Imran Haider',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {10.1: {'batsman': "KJ O'Brien",
   'bowler': 'Ahmed Raza',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {10.2: {'batsman': "KJ O'Brien",
   'bowler': 'Ahmed Raza',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {10.3: {'batsman': 'GC Wilson',
   'bowler': 'Ahmed Raza',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {10.4: {'batsman': "KJ O'Brien",
   'bowler': 'Ahmed Raza',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {10.5: {'batsman': "KJ O'Brien",
   'bowler': 'Ahmed Raza',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {10.6: {'batsman': 'GC Wilson',
   'bowler': 'Ahmed Raza',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {11.1: {'batsman': 'GC Wilson',
   'bowler': 'Imran Haider',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {11.2: {'batsman': 'GC Wilson',
   'bowler': 'Imran Haider',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {11.3: {'batsman': 'GC Wilson',
   'bowler': 'Imran Haider',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {11.4: {'batsman': "KJ O'Brien",
   'bowler': 'Imran Haider',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {11.5: {'batsman': "KJ O'Brien",
   'bowler': 'Imran Haider',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {11.6: {'batsman': "KJ O'Brien",
   'bowler': 'Imran Haider',
   'extras': {'legbyes': 1},
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {12.1: {'batsman': "KJ O'Brien",
   'bowler': 'Ahmed Raza',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {12.2: {'batsman': "KJ O'Brien",
   'bowler': 'Ahmed Raza',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {12.3: {'batsman': "KJ O'Brien",
   'bowler': 'Ahmed Raza',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {12.4: {'batsman': "KJ O'Brien",
   'bowler': 'Ahmed Raza',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {12.5: {'batsman': 'GC Wilson',
   'bowler': 'Ahmed Raza',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {12.6: {'batsman': 'GC Wilson',
   'bowler': 'Ahmed Raza',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {13.1: {'batsman': "KJ O'Brien",
   'bowler': 'Zahoor Khan',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.2: {'batsman': 'GC Wilson',
   'bowler': 'Zahoor Khan',
   'non_striker': "KJ O'Brien",
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.3: {'batsman': "KJ O'Brien",
   'bowler': 'Zahoor Khan',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['Imran Haider'],
    'kind': 'caught',
    'player_out': "KJ O'Brien"}}},
 {13.4: {'batsman': 'GJ Thompson',
   'bowler': 'Zahoor Khan',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.5: {'batsman': 'GC Wilson',
   'bowler': 'Zahoor Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.6: {'batsman': 'GJ Thompson',
   'bowler': 'Zahoor Khan',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.1: {'batsman': 'GJ Thompson',
   'bowler': 'Imran Haider',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.2: {'batsman': 'GC Wilson',
   'bowler': 'Imran Haider',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {14.3: {'batsman': 'GC Wilson',
   'bowler': 'Imran Haider',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {14.4: {'batsman': 'GC Wilson',
   'bowler': 'Imran Haider',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {14.5: {'batsman': 'GC Wilson',
   'bowler': 'Imran Haider',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.6: {'batsman': 'GJ Thompson',
   'bowler': 'Imran Haider',
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {15.1: {'batsman': 'GC Wilson',
   'bowler': 'Zahoor Khan',
   'extras': {'legbyes': 1},
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {15.2: {'batsman': 'GJ Thompson',
   'bowler': 'Zahoor Khan',
   'extras': {'legbyes': 1},
   'non_striker': 'GC Wilson',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {15.3: {'batsman': 'GC Wilson',
   'bowler': 'Zahoor Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {15.4: {'batsman': 'GC Wilson',
   'bowler': 'Zahoor Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['Ghulam Shabber'],
    'kind': 'caught',
    'player_out': 'GC Wilson'}}},
 {15.5: {'batsman': 'AR McBrine',
   'bowler': 'Zahoor Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {15.6: {'batsman': 'GJ Thompson',
   'bowler': 'Zahoor Khan',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.1: {'batsman': 'GJ Thompson',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.2: {'batsman': 'AR McBrine',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {16.3: {'batsman': 'AR McBrine',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {16.4: {'batsman': 'AR McBrine',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {16.5: {'batsman': 'AR McBrine',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.6: {'batsman': 'GJ Thompson',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.1: {'batsman': 'GJ Thompson',
   'bowler': 'Zahoor Khan',
   'extras': {'wides': 1},
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {17.2: {'batsman': 'GJ Thompson',
   'bowler': 'Zahoor Khan',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.3: {'batsman': 'AR McBrine',
   'bowler': 'Zahoor Khan',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.4: {'batsman': 'GJ Thompson',
   'bowler': 'Zahoor Khan',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {17.5: {'batsman': 'GJ Thompson',
   'bowler': 'Zahoor Khan',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {17.6: {'batsman': 'GJ Thompson',
   'bowler': 'Zahoor Khan',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {17.7: {'batsman': 'GJ Thompson',
   'bowler': 'Zahoor Khan',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {18.1: {'batsman': 'AR McBrine',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'GJ Thompson',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {18.2: {'batsman': 'GJ Thompson',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'kind': 'bowled', 'player_out': 'GJ Thompson'}}},
 {18.3: {'batsman': 'GH Dockrell',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {18.4: {'batsman': 'AR McBrine',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'GH Dockrell',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {18.5: {'batsman': 'AR McBrine',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'GH Dockrell',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {18.6: {'batsman': 'AR McBrine',
   'bowler': 'Mohammad Naveed',
   'non_striker': 'GH Dockrell',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {19.1: {'batsman': 'AR McBrine',
   'bowler': 'Zahoor Khan',
   'extras': {'legbyes': 1},
   'non_striker': 'GH Dockrell',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {19.2: {'batsman': 'GH Dockrell',
   'bowler': 'Zahoor Khan',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {19.3: {'batsman': 'AR McBrine',
   'bowler': 'Zahoor Khan',
   'extras': {'byes': 1},
   'non_striker': 'GH Dockrell',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {19.4: {'batsman': 'GH Dockrell',
   'bowler': 'Zahoor Khan',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {19.5: {'batsman': 'AR McBrine',
   'bowler': 'Zahoor Khan',
   'non_striker': 'GH Dockrell',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {19.6: {'batsman': 'GH Dockrell',
   'bowler': 'Zahoor Khan',
   'non_striker': 'AR McBrine',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}}]

In [44]:
count = 1
# Initialize an empty list to store DataFrames
all_delivery_dataframes = []

for index, row in matches.iterrows():
    if count in [75,108,150,180,268,360,443,458,584,748,982,1052,1111,1226,1345]:
        count+=1
        continue
    count+=1
    ball_of_match = []
    batsman = []
    bowler = []
    runs = []
    player_of_dismissed = []
    teams = []
    batting_team = []
    match_id = []
    city = []
    venue = []

    # Ensure 'innings' key exists and is a list before proceeding
    if 'innings' in row and isinstance(row['innings'], list) and len(row['innings']) > 0:
        first_innings = row['innings'][0].get('1st innings')
        if first_innings and 'deliveries' in first_innings and isinstance(first_innings['deliveries'], list):
            for ball in first_innings['deliveries']:
                for key in ball.keys():
                    match_id.append(count)
                    batting_team.append(first_innings['team'])
                    teams.append(row['info.teams'])
                    ball_of_match.append(key)
                    batsman.append(ball[key]['batsman'])
                    bowler.append(ball[key]['bowler'])
                    runs.append(ball[key]['runs']['total'])
                    city.append(row['info.city'])
                    venue.append(row['info.venue'])
                    try:
                        player_of_dismissed.append(ball[key]['wicket']['player_out'])
                    except:
                        player_of_dismissed.append('0')

            # Create a DataFrame for the current match's deliveries
            loop_df = pd.DataFrame({
                    'match_id':match_id,
                    'teams':teams,
                    'batting_team':batting_team,
                    'ball':ball_of_match,
                    'batsman':batsman,
                    'bowler':bowler,
                    'runs':runs,
                    'player_dismissed':player_of_dismissed,
                    'city':city,
                    'venue':venue
                })
            all_delivery_dataframes.append(loop_df)
        else:
            print(f"Skipping match_id {count} due to missing or invalid '1st innings' or 'deliveries' data.")
    else:
        print(f"Skipping match_id {count} due to missing or invalid 'innings' data.")

# Concatenate all collected DataFrames outside the loop
delivery_df = pd.concat(all_delivery_dataframes, ignore_index=True)
display(delivery_df.head())

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue
0,2,"[United Arab Emirates, Ireland]",Ireland,0.1,PR Stirling,Mohammad Naveed,1,0,NaN,Dubai International Cricket Stadium
1,2,"[United Arab Emirates, Ireland]",Ireland,0.2,PR Stirling,Mohammad Naveed,0,0,NaN,Dubai International Cricket Stadium
2,2,"[United Arab Emirates, Ireland]",Ireland,0.3,PR Stirling,Mohammad Naveed,0,0,NaN,Dubai International Cricket Stadium
3,2,"[United Arab Emirates, Ireland]",Ireland,0.4,PR Stirling,Mohammad Naveed,0,0,NaN,Dubai International Cricket Stadium
4,2,"[United Arab Emirates, Ireland]",Ireland,0.5,PR Stirling,Mohammad Naveed,0,0,NaN,Dubai International Cricket Stadium

In [45]:
delivery_df.shape

(404301, 10)

In [46]:
def bowl(row):
    for team in row['teams']:
        if team != row['batting_team']:
            return team

In [47]:
delivery_df['bowling_team'] = delivery_df.apply(bowl,axis=1)

In [48]:
delivery_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,"[United Arab Emirates, Ireland]",Ireland,0.1,PR Stirling,Mohammad Naveed,1,0,NaN,Dubai International Cricket Stadium,United Arab Emirates
1,2,"[United Arab Emirates, Ireland]",Ireland,0.2,PR Stirling,Mohammad Naveed,0,0,NaN,Dubai International Cricket Stadium,United Arab Emirates
2,2,"[United Arab Emirates, Ireland]",Ireland,0.3,PR Stirling,Mohammad Naveed,0,0,NaN,Dubai International Cricket Stadium,United Arab Emirates
3,2,"[United Arab Emirates, Ireland]",Ireland,0.4,PR Stirling,Mohammad Naveed,0,0,NaN,Dubai International Cricket Stadium,United Arab Emirates
4,2,"[United Arab Emirates, Ireland]",Ireland,0.5,PR Stirling,Mohammad Naveed,0,0,NaN,Dubai International Cricket Stadium,United Arab Emirates
...,...,...,...,...,...,...,...,...,...,...,...
404296,3359,"[Pakistan, New Zealand]",Pakistan,19.2,Imad Wasim,TG Southee,1,0,Abu Dhabi,Sheikh Zayed Stadium,New Zealand
404297,3359,"[Pakistan, New Zealand]",Pakistan,19.3,Faheem Ashraf,TG Southee,0,0,Abu Dhabi,Sheikh Zayed Stadium,New Zealand
404298,3359,"[Pakistan, New Zealand]",Pakistan,19.4,Faheem Ashraf,TG Southee,1,0,Abu Dhabi,Sheikh Zayed Stadium,New Zealand
404299,3359,"[Pakistan, New Zealand]",Pakistan,19.5,Imad Wasim,TG Southee,4,0,Abu Dhabi,Sheikh Zayed Stadium,New Zealand
404300,3359,"[Pakistan, New Zealand]",Pakistan,19.6,Imad Wasim,TG Southee,6,0,Abu Dhabi,Sheikh Zayed Stadium,New Zealand

In [49]:
delivery_df.drop(columns=['teams'],inplace=True)

In [50]:
delivery_df['batting_team'].unique()

array(['Ireland', 'Kenya', 'Bangladesh', 'Mozambique', 'Sri Lanka',
       'Nepal', 'Uganda', 'Hong Kong', 'Zimbabwe', 'Canada', 'England',
       'Rwanda', 'Australia', 'India', 'Nigeria', 'South Africa',
       'Norway', 'West Indies', 'Pakistan', 'Vanuatu', 'Singapore',
       'Saudi Arabia', 'Bahrain', 'Denmark', 'Botswana', 'Malta',
       'Gibraltar', 'United Arab Emirates', 'Ghana', 'New Zealand',
       'Guernsey', 'Papua New Guinea', 'Malawi', 'Scotland', 'Spain',
       'United States of America', 'Malaysia', 'Namibia', 'France',
       'Slovenia', 'Portugal', 'Italy', 'Switzerland', 'Thailand',
       'Cambodia', 'Brazil', 'Belgium', 'Argentina', 'Austria',
       'Tanzania', 'Indonesia', 'Mexico', 'Bhutan', 'Oman', 'Germany',
       'Cyprus', 'Costa Rica', 'Myanmar', 'Japan', 'Mali', 'Romania',
       'Seychelles', 'Finland', 'Hungary', 'Bahamas', 'Croatia', 'Jersey',
       'Bermuda', 'Panama', 'Kuwait', 'Sweden', 'Swaziland', 'Estonia',
       'Netherlands', 'Czech Republic', 'Sierra Leone', 'Cayman Islands',
       'Philippines', 'Serbia', 'Eswatini', 'Timor-Leste', 'China',
       'Samoa', 'Maldives', 'Fiji', 'Ivory Coast', 'Bulgaria',
       'Cook Islands', 'Lesotho', 'Suriname', 'Israel', 'St Helena',
       'Iran', 'Cameroon', 'Belize', 'Luxembourg', 'Mongolia', 'Qatar',
       'Isle of Man', 'Zambia', 'South Korea', 'Turkey', 'Greece',
       'Turks and Caicos Island', 'Gambia', 'Chile'], dtype=object)

In [51]:
teams = [
    'Australia',
    'India',
    'Bangladesh',
    'New Zealand',
    'South Africa',
    'England',
    'West Indies',
    'Afghanistan',
    'Pakistan',
    'Sri Lanka'
]

In [52]:
delivery_df = delivery_df[delivery_df['batting_team'].isin(teams)]
delivery_df = delivery_df[delivery_df['bowling_team'].isin(teams)]

In [53]:
delivery_df

,match_id,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
245,4,Bangladesh,0.1,Nazmul Hossain Shanto,Shaheen Shah Afridi,0,0,Adelaide,Adelaide Oval,Pakistan
246,4,Bangladesh,0.2,Nazmul Hossain Shanto,Shaheen Shah Afridi,1,0,Adelaide,Adelaide Oval,Pakistan
247,4,Bangladesh,0.3,Liton Das,Shaheen Shah Afridi,1,0,Adelaide,Adelaide Oval,Pakistan
248,4,Bangladesh,0.4,Nazmul Hossain Shanto,Shaheen Shah Afridi,4,0,Adelaide,Adelaide Oval,Pakistan
249,4,Bangladesh,0.5,Nazmul Hossain Shanto,Shaheen Shah Afridi,0,0,Adelaide,Adelaide Oval,Pakistan
...,...,...,...,...,...,...,...,...,...,...
404296,3359,Pakistan,19.2,Imad Wasim,TG Southee,1,0,Abu Dhabi,Sheikh Zayed Stadium,New Zealand
404297,3359,Pakistan,19.3,Faheem Ashraf,TG Southee,0,0,Abu Dhabi,Sheikh Zayed Stadium,New Zealand
404298,3359,Pakistan,19.4,Faheem Ashraf,TG Southee,1,0,Abu Dhabi,Sheikh Zayed Stadium,New Zealand
404299,3359,Pakistan,19.5,Imad Wasim,TG Southee,4,0,Abu Dhabi,Sheikh Zayed Stadium,New Zealand
404300,3359,Pakistan,19.6,Imad Wasim,TG Southee,6,0,Abu Dhabi,Sheikh Zayed Stadium,New Zealand

In [54]:
output = delivery_df[['match_id','batting_team','bowling_team','ball','runs','player_dismissed','city','venue']]

In [55]:
output

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
245,4,Bangladesh,Pakistan,0.1,0,0,Adelaide,Adelaide Oval
246,4,Bangladesh,Pakistan,0.2,1,0,Adelaide,Adelaide Oval
247,4,Bangladesh,Pakistan,0.3,1,0,Adelaide,Adelaide Oval
248,4,Bangladesh,Pakistan,0.4,4,0,Adelaide,Adelaide Oval
249,4,Bangladesh,Pakistan,0.5,0,0,Adelaide,Adelaide Oval
...,...,...,...,...,...,...,...,...
404296,3359,Pakistan,New Zealand,19.2,1,0,Abu Dhabi,Sheikh Zayed Stadium
404297,3359,Pakistan,New Zealand,19.3,0,0,Abu Dhabi,Sheikh Zayed Stadium
404298,3359,Pakistan,New Zealand,19.4,1,0,Abu Dhabi,Sheikh Zayed Stadium
404299,3359,Pakistan,New Zealand,19.5,4,0,Abu Dhabi,Sheikh Zayed Stadium
404300,3359,Pakistan,New Zealand,19.6,6,0,Abu Dhabi,Sheikh Zayed Stadium

In [56]:
pickle.dump(output,open('dataset_level2.pkl','wb'))