In [105]:
import pandas as pd
import pickle
import numpy as np

In [106]:
df = pickle.load(open('/content/dataset_level2.pkl','rb'))

In [107]:
df

# batting_team
# bowling team
# city
# current score
# ball left
# wickets left
# current rr
# last five

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
245,4,Bangladesh,Pakistan,0.1,0,0,Adelaide,Adelaide Oval
246,4,Bangladesh,Pakistan,0.2,1,0,Adelaide,Adelaide Oval
247,4,Bangladesh,Pakistan,0.3,1,0,Adelaide,Adelaide Oval
248,4,Bangladesh,Pakistan,0.4,4,0,Adelaide,Adelaide Oval
249,4,Bangladesh,Pakistan,0.5,0,0,Adelaide,Adelaide Oval
...,...,...,...,...,...,...,...,...
404296,3359,Pakistan,New Zealand,19.2,1,0,Abu Dhabi,Sheikh Zayed Stadium
404297,3359,Pakistan,New Zealand,19.3,0,0,Abu Dhabi,Sheikh Zayed Stadium
404298,3359,Pakistan,New Zealand,19.4,1,0,Abu Dhabi,Sheikh Zayed Stadium
404299,3359,Pakistan,New Zealand,19.5,4,0,Abu Dhabi,Sheikh Zayed Stadium
404300,3359,Pakistan,New Zealand,19.6,6,0,Abu Dhabi,Sheikh Zayed Stadium

In [108]:
df.isnull().sum()

match_id               0
batting_team           0
bowling_team           0
ball                   0
runs                   0
player_dismissed       0
city                8549
venue                  0
dtype: int64

In [109]:
df[df['city'].isnull()]['venue'].value_counts()

venue
Dubai International Cricket Stadium        3092
Pallekele International Cricket Stadium    2066
Melbourne Cricket Ground                   1453
Sydney Cricket Ground                       749
Adelaide Oval                               498
Harare Sports Club                          372
Sylhet International Cricket Stadium        128
Sharjah Cricket Stadium                     127
Carrara Oval                                 64
Name: count, dtype: int64

In [110]:
cities = np.where(df['city'].isnull(),df['venue'].str.split().apply(lambda x:x[0]),df['city'])

In [111]:
df['city'] = cities

In [112]:
df.isnull().sum()

match_id            0
batting_team        0
bowling_team        0
ball                0
runs                0
player_dismissed    0
city                0
venue               0
dtype: int64

In [113]:
df.drop(columns=['venue'],inplace=True)

In [114]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
245,4,Bangladesh,Pakistan,0.1,0,0,Adelaide
246,4,Bangladesh,Pakistan,0.2,1,0,Adelaide
247,4,Bangladesh,Pakistan,0.3,1,0,Adelaide
248,4,Bangladesh,Pakistan,0.4,4,0,Adelaide
249,4,Bangladesh,Pakistan,0.5,0,0,Adelaide
...,...,...,...,...,...,...,...
404296,3359,Pakistan,New Zealand,19.2,1,0,Abu Dhabi
404297,3359,Pakistan,New Zealand,19.3,0,0,Abu Dhabi
404298,3359,Pakistan,New Zealand,19.4,1,0,Abu Dhabi
404299,3359,Pakistan,New Zealand,19.5,4,0,Abu Dhabi
404300,3359,Pakistan,New Zealand,19.6,6,0,Abu Dhabi

In [115]:
eligible_cities = df['city'].value_counts()[df['city'].value_counts() > 600].index.tolist()

In [116]:
df = df[df['city'].isin(eligible_cities)].copy()

In [117]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
245,4,Bangladesh,Pakistan,0.1,0,0,Adelaide
246,4,Bangladesh,Pakistan,0.2,1,0,Adelaide
247,4,Bangladesh,Pakistan,0.3,1,0,Adelaide
248,4,Bangladesh,Pakistan,0.4,4,0,Adelaide
249,4,Bangladesh,Pakistan,0.5,0,0,Adelaide
...,...,...,...,...,...,...,...
404296,3359,Pakistan,New Zealand,19.2,1,0,Abu Dhabi
404297,3359,Pakistan,New Zealand,19.3,0,0,Abu Dhabi
404298,3359,Pakistan,New Zealand,19.4,1,0,Abu Dhabi
404299,3359,Pakistan,New Zealand,19.5,4,0,Abu Dhabi
404300,3359,Pakistan,New Zealand,19.6,6,0,Abu Dhabi

In [118]:
df['runs'] = pd.to_numeric(df['runs'], errors='coerce').fillna(0).astype(int)

df['current_score'] = df.groupby('match_id')['runs'].cumsum()

In [119]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score
245,4,Bangladesh,Pakistan,0.1,0,0,Adelaide,0
246,4,Bangladesh,Pakistan,0.2,1,0,Adelaide,1
247,4,Bangladesh,Pakistan,0.3,1,0,Adelaide,2
248,4,Bangladesh,Pakistan,0.4,4,0,Adelaide,6
249,4,Bangladesh,Pakistan,0.5,0,0,Adelaide,6
...,...,...,...,...,...,...,...,...
404296,3359,Pakistan,New Zealand,19.2,1,0,Abu Dhabi,137
404297,3359,Pakistan,New Zealand,19.3,0,0,Abu Dhabi,137
404298,3359,Pakistan,New Zealand,19.4,1,0,Abu Dhabi,138
404299,3359,Pakistan,New Zealand,19.5,4,0,Abu Dhabi,142
404300,3359,Pakistan,New Zealand,19.6,6,0,Abu Dhabi,148

In [120]:
df['over'] = df['ball'].apply(lambda x:str(x).split(".")[0])
df['ball_no'] = df['ball'].apply(lambda x:str(x).split(".")[1])
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no
245,4,Bangladesh,Pakistan,0.1,0,0,Adelaide,0,0,1
246,4,Bangladesh,Pakistan,0.2,1,0,Adelaide,1,0,2
247,4,Bangladesh,Pakistan,0.3,1,0,Adelaide,2,0,3
248,4,Bangladesh,Pakistan,0.4,4,0,Adelaide,6,0,4
249,4,Bangladesh,Pakistan,0.5,0,0,Adelaide,6,0,5
...,...,...,...,...,...,...,...,...,...,...
404296,3359,Pakistan,New Zealand,19.2,1,0,Abu Dhabi,137,19,2
404297,3359,Pakistan,New Zealand,19.3,0,0,Abu Dhabi,137,19,3
404298,3359,Pakistan,New Zealand,19.4,1,0,Abu Dhabi,138,19,4
404299,3359,Pakistan,New Zealand,19.5,4,0,Abu Dhabi,142,19,5
404300,3359,Pakistan,New Zealand,19.6,6,0,Abu Dhabi,148,19,6

In [121]:
df['balls_bowled'] = (df['over'].astype('int')*6) + df['ball_no'].astype('int')
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled
245,4,Bangladesh,Pakistan,0.1,0,0,Adelaide,0,0,1,1
246,4,Bangladesh,Pakistan,0.2,1,0,Adelaide,1,0,2,2
247,4,Bangladesh,Pakistan,0.3,1,0,Adelaide,2,0,3,3
248,4,Bangladesh,Pakistan,0.4,4,0,Adelaide,6,0,4,4
249,4,Bangladesh,Pakistan,0.5,0,0,Adelaide,6,0,5,5
...,...,...,...,...,...,...,...,...,...,...,...
404296,3359,Pakistan,New Zealand,19.2,1,0,Abu Dhabi,137,19,2,116
404297,3359,Pakistan,New Zealand,19.3,0,0,Abu Dhabi,137,19,3,117
404298,3359,Pakistan,New Zealand,19.4,1,0,Abu Dhabi,138,19,4,118
404299,3359,Pakistan,New Zealand,19.5,4,0,Abu Dhabi,142,19,5,119
404300,3359,Pakistan,New Zealand,19.6,6,0,Abu Dhabi,148,19,6,120

In [122]:
df['balls_left'] = 120 - df['balls_bowled']
df['balls_left'] = df['balls_left'].apply(lambda x:0 if x<0 else x)
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left
245,4,Bangladesh,Pakistan,0.1,0,0,Adelaide,0,0,1,1,119
246,4,Bangladesh,Pakistan,0.2,1,0,Adelaide,1,0,2,2,118
247,4,Bangladesh,Pakistan,0.3,1,0,Adelaide,2,0,3,3,117
248,4,Bangladesh,Pakistan,0.4,4,0,Adelaide,6,0,4,4,116
249,4,Bangladesh,Pakistan,0.5,0,0,Adelaide,6,0,5,5,115
...,...,...,...,...,...,...,...,...,...,...,...,...
404296,3359,Pakistan,New Zealand,19.2,1,0,Abu Dhabi,137,19,2,116,4
404297,3359,Pakistan,New Zealand,19.3,0,0,Abu Dhabi,137,19,3,117,3
404298,3359,Pakistan,New Zealand,19.4,1,0,Abu Dhabi,138,19,4,118,2
404299,3359,Pakistan,New Zealand,19.5,4,0,Abu Dhabi,142,19,5,119,1
404300,3359,Pakistan,New Zealand,19.6,6,0,Abu Dhabi,148,19,6,120,0

In [123]:
df['player_dismissed'] = (
    (df['player_dismissed'] != '0')
    .astype(int)
)

df['player_dismissed'] = (
    df.groupby('match_id')['player_dismissed']
      .cumsum()
)

df['wickets_left'] = 10 - df['player_dismissed']

In [124]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,wickets_left
245,4,Bangladesh,Pakistan,0.1,0,0,Adelaide,0,0,1,1,119,10
246,4,Bangladesh,Pakistan,0.2,1,0,Adelaide,1,0,2,2,118,10
247,4,Bangladesh,Pakistan,0.3,1,0,Adelaide,2,0,3,3,117,10
248,4,Bangladesh,Pakistan,0.4,4,0,Adelaide,6,0,4,4,116,10
249,4,Bangladesh,Pakistan,0.5,0,0,Adelaide,6,0,5,5,115,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
404296,3359,Pakistan,New Zealand,19.2,1,6,Abu Dhabi,137,19,2,116,4,4
404297,3359,Pakistan,New Zealand,19.3,0,6,Abu Dhabi,137,19,3,117,3,4
404298,3359,Pakistan,New Zealand,19.4,1,6,Abu Dhabi,138,19,4,118,2,4
404299,3359,Pakistan,New Zealand,19.5,4,6,Abu Dhabi,142,19,5,119,1,4
404300,3359,Pakistan,New Zealand,19.6,6,6,Abu Dhabi,148,19,6,120,0,4

In [125]:
df['crr'] = (df['current_score']*6)/df['balls_bowled']

In [126]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,wickets_left,crr
245,4,Bangladesh,Pakistan,0.1,0,0,Adelaide,0,0,1,1,119,10,0.000000
246,4,Bangladesh,Pakistan,0.2,1,0,Adelaide,1,0,2,2,118,10,3.000000
247,4,Bangladesh,Pakistan,0.3,1,0,Adelaide,2,0,3,3,117,10,4.000000
248,4,Bangladesh,Pakistan,0.4,4,0,Adelaide,6,0,4,4,116,10,9.000000
249,4,Bangladesh,Pakistan,0.5,0,0,Adelaide,6,0,5,5,115,10,7.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404296,3359,Pakistan,New Zealand,19.2,1,6,Abu Dhabi,137,19,2,116,4,4,7.086207
404297,3359,Pakistan,New Zealand,19.3,0,6,Abu Dhabi,137,19,3,117,3,4,7.025641
404298,3359,Pakistan,New Zealand,19.4,1,6,Abu Dhabi,138,19,4,118,2,4,7.016949
404299,3359,Pakistan,New Zealand,19.5,4,6,Abu Dhabi,142,19,5,119,1,4,7.159664
404300,3359,Pakistan,New Zealand,19.6,6,6,Abu Dhabi,148,19,6,120,0,4,7.400000

In [127]:
groups = df.groupby('match_id')

match_ids = df['match_id'].unique()
last_five = []

for id in match_ids:
    match_df = groups.get_group(id)
    last_five.extend(
        match_df['runs']
        .rolling(window=30, min_periods=1)
        .sum()
        .tolist()
    )

df['last_five'] = last_five

In [128]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,wickets_left,crr,last_five
245,4,Bangladesh,Pakistan,0.1,0,0,Adelaide,0,0,1,1,119,10,0.000000,0.0
246,4,Bangladesh,Pakistan,0.2,1,0,Adelaide,1,0,2,2,118,10,3.000000,1.0
247,4,Bangladesh,Pakistan,0.3,1,0,Adelaide,2,0,3,3,117,10,4.000000,2.0
248,4,Bangladesh,Pakistan,0.4,4,0,Adelaide,6,0,4,4,116,10,9.000000,6.0
249,4,Bangladesh,Pakistan,0.5,0,0,Adelaide,6,0,5,5,115,10,7.200000,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
404296,3359,Pakistan,New Zealand,19.2,1,6,Abu Dhabi,137,19,2,116,4,4,7.086207,42.0
404297,3359,Pakistan,New Zealand,19.3,0,6,Abu Dhabi,137,19,3,117,3,4,7.025641,38.0
404298,3359,Pakistan,New Zealand,19.4,1,6,Abu Dhabi,138,19,4,118,2,4,7.016949,38.0
404299,3359,Pakistan,New Zealand,19.5,4,6,Abu Dhabi,142,19,5,119,1,4,7.159664,41.0
404300,3359,Pakistan,New Zealand,19.6,6,6,Abu Dhabi,148,19,6,120,0,4,7.400000,47.0

In [129]:
final_df = df.groupby('match_id').sum()['runs'].reset_index().merge(df,on='match_id')

In [130]:
final_df

,match_id,runs_x,batting_team,bowling_team,ball,runs_y,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,wickets_left,crr,last_five
0,4,127,Bangladesh,Pakistan,0.1,0,0,Adelaide,0,0,1,1,119,10,0.000000,0.0
1,4,127,Bangladesh,Pakistan,0.2,1,0,Adelaide,1,0,2,2,118,10,3.000000,1.0
2,4,127,Bangladesh,Pakistan,0.3,1,0,Adelaide,2,0,3,3,117,10,4.000000,2.0
3,4,127,Bangladesh,Pakistan,0.4,4,0,Adelaide,6,0,4,4,116,10,9.000000,6.0
4,4,127,Bangladesh,Pakistan,0.5,0,0,Adelaide,6,0,5,5,115,10,7.200000,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98298,3359,148,Pakistan,New Zealand,19.2,1,6,Abu Dhabi,137,19,2,116,4,4,7.086207,42.0
98299,3359,148,Pakistan,New Zealand,19.3,0,6,Abu Dhabi,137,19,3,117,3,4,7.025641,38.0
98300,3359,148,Pakistan,New Zealand,19.4,1,6,Abu Dhabi,138,19,4,118,2,4,7.016949,38.0
98301,3359,148,Pakistan,New Zealand,19.5,4,6,Abu Dhabi,142,19,5,119,1,4,7.159664,41.0
98302,3359,148,Pakistan,New Zealand,19.6,6,6,Abu Dhabi,148,19,6,120,0,4,7.400000,47.0

In [131]:
final_df=final_df[['batting_team','bowling_team','city','current_score','balls_left','wickets_left','crr','last_five','runs_x']]

In [132]:
final_df

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five,runs_x
0,Bangladesh,Pakistan,Adelaide,0,119,10,0.000000,0.0,127
1,Bangladesh,Pakistan,Adelaide,1,118,10,3.000000,1.0,127
2,Bangladesh,Pakistan,Adelaide,2,117,10,4.000000,2.0,127
3,Bangladesh,Pakistan,Adelaide,6,116,10,9.000000,6.0,127
4,Bangladesh,Pakistan,Adelaide,6,115,10,7.200000,6.0,127
...,...,...,...,...,...,...,...,...,...
98298,Pakistan,New Zealand,Abu Dhabi,137,4,4,7.086207,42.0,148
98299,Pakistan,New Zealand,Abu Dhabi,137,3,4,7.025641,38.0,148
98300,Pakistan,New Zealand,Abu Dhabi,138,2,4,7.016949,38.0,148
98301,Pakistan,New Zealand,Abu Dhabi,142,1,4,7.159664,41.0,148
98302,Pakistan,New Zealand,Abu Dhabi,148,0,4,7.400000,47.0,148

In [133]:
final_df.dropna(inplace=True)

/tmp/ipykernel_10742/2709626079.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.dropna(inplace=True)

In [134]:
final_df.isnull().sum()

batting_team     0
bowling_team     0
city             0
current_score    0
balls_left       0
wickets_left     0
crr              0
last_five        0
runs_x           0
dtype: int64

In [135]:
final_df.shape

(98303, 9)

In [136]:
final_df = final_df.sample(final_df.shape[0])

In [137]:
final_df.sample(2)

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five,runs_x
34697,India,New Zealand,Mount Maunganui,64,69,9,7.529412,36.0,163
89642,West Indies,Pakistan,Barbados,38,72,6,4.750000,20.0,111

In [138]:
X = final_df.drop(columns=['runs_x'])
y = final_df['runs_x']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [139]:
X_train

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five
46994,New Zealand,Sri Lanka,Johannesburg,146,15,5,8.342857,44.0
22710,West Indies,Sri Lanka,Colombo,149,8,4,7.982143,43.0
62205,New Zealand,Australia,Sydney,34,106,10,14.571429,34.0
67344,South Africa,West Indies,Tarouba,7,100,10,2.100000,7.0
57187,West Indies,Australia,Gros Islet,107,23,5,6.618557,46.0
...,...,...,...,...,...,...,...,...
90814,West Indies,Australia,Basseterre,186,17,8,10.834951,53.0
83923,West Indies,England,Bristol,55,83,9,8.918919,51.0
66829,Pakistan,West Indies,Lauderhill,152,15,9,8.685714,40.0
81919,England,India,Birmingham,18,109,10,9.818182,18.0
76967,New Zealand,England,Chester-le-Street,55,69,6,6.470588,30.0

In [140]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score,mean_absolute_error

In [141]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

trf = ColumnTransformer(
    transformers=[
        ('trf',
         OneHotEncoder(sparse_output=False, drop='first'),
         ['batting_team', 'bowling_team', 'city'])
    ],
    remainder='passthrough'
)

In [142]:
pipe = Pipeline(steps=[
    ('step1',trf),
    ('step3',XGBRegressor(n_estimators=1000,learning_rate=0.2,max_depth=12,random_state=1))
])

In [143]:
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.948323130607605
3.0819334983825684

In [144]:
pickle.dump(pipe,open('pipe.pkl','wb'))